---
services:
  gateway:
    image: bwdesigngroup/ignition-docker:8.1.32
    hostname: APC
    volumes:
      - ./ignition-data:/workdir
      - ./backups/gateway.gwbk:/restore.gwbk
    environment:
      SYMLINK_GITIGNORE: false
      SYMLINK_LOGBACK: false
      GATEWAY_SYSTEM_NAME: APC
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: APC.localtest.me
      GATEWAY_MODULES_ENABLED: vision,perspective,allen-bradley-drivers,opc-ua,tag-historian
    labels:
      traefik.enable: "true"
      traefik.hostname: "APC"
    command: >
      -r /restore.gwbk
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
